### ISSUE TITLE
Adaptar APP para o padrão do SIM808

### ISSUE THREAD

**Issue by felipebastosb** [lasseufpa/circular#26]
Quando é feito o pedido das coordenadas para o SIM808 ele retorna em alguns formatos específicos, acho que para evitar tratamento de strings no hardware é melhor adaptar no APP, deem uma olhada no formato que vamos enviar (publicar) no documento em anexo. Onde ele fala da resposta que será enviada inicia na pagina 10 e vai até a 12.

[GNSS](https://www.elecrow.com/download/SIM800%20Series_GNSS_Application%20Note%20V1.00.pdf)

**Comment by albertklik** [comment]
O app está reconhecendo informações de localização no formato:

`#NCircular01*#X-4.508526*#Y-56.985413516*`

o Shield GPS que usaremos dispara atalizações de localização no formato:

`+CGNSINF: 1,1,20170606213815.000,-1.464823,-48.445460,25.900,1.74,13.6,1,,4.4,4.5,1.0,,13,3,,,37,,`

basicamente irei construir uma classe chamada `LocationInfo` com os dados do Shield, e enviar ao objeto circular com um método `ChangeLocation (LocationInfo) {...}`

**Comment by felipebastosb** [comment]
Algumas informações foram trocadas:

Passaremos o nome do circular no tópico pelo seguinte padrão:
/ufpa/circular/loc/01

onde depois da última barra vem o número do circular

Ex:
/ufpa/circular/loc/01 - Circular 01
/ufpa/circular/loc/02 - Circular 02
/ufpa/circular/loc/03 - Circular 03

Outro ponto é que eventualmente ao invés de chegar:

+CGNSINF: 1,1,20170606213815.000,-1.464823,-48.445460,25.900,1.74,13.6,1,,4.4,4.5,1.0,,13,3,,,37,,

Pode chegar:

+CGNSINF+CGNSINF:1,1,20170606213815.000,-1.464823,-48.445460,25.900,1.74,13.6,1,,4.4,4.5,1.0,,13,3,,,37,,

Os sensores de temperatura e umidade estão funcionando e seus tópicos são:

"/ufpa/circular/enviroment/temp/01" Temperatura circular 1
"/ufpa/circular/enviroment/hum/01" Umidade circular 1
"/ufpa/circular/enviroment/cac/01" indeixe de calor circular 1

"/ufpa/circular/enviroment/temp/02" Temperatura circular 2
"/ufpa/circular/enviroment/hum/02" Umidade circular 2
"/ufpa/circular/enviroment/cac/02" indeixe de calor circular 2

O padrão é:

/ufpa/circular/enviroment/data(temp, humidity...)/XX(number of the bus)

**Comment by felipebastosb** [comment]
Uma dica é usar wildcards, desse jeito se tu se subscrever para o tópico "/ufpa/circular/loc/+" ou "/ufpa/circular/loc/#" vais estar subscrito nos "/ufpa/circular/loc/01...02....02" usando o + ou # ele pega qualquer coisa que tenha depois da ultima barra. Aí e só verificar qual o final do tópico pra saber de qual ônibus veio a informação.

Podem olhar mais sobre isso aqui: http://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices

**Comment by albertklik** [comment]
vou primeiro adaptar a coleta de informações, depois verei a questão do tópico

**Comment by albertklik** [comment]
não tem como adicionar o nome do circular junto com a mensagem? isso facilitaria bastante o trabalho

**Comment by albertklik** [comment]
Concluído, o aplicativo já esta reconhecendo mensagens de localização no novo padrão
O aplicativo, por enquanto está ouvindo no tópico /ufpa/circular/loc/, eu ainda preciso achar uma forma de  capturar o nome do circular pelo endereço do tópico.

**Comment by albertklik** [comment]
aguardando a mensagem do felipe para fechar a issue
