### ISSUE TITLE
Adaptar site para o padrão do SIM808

### ISSUE THREAD

**Issue by felipebastosb** [lasseufpa/circular#27]
Quando é feito o pedido das coordenadas para o SIM808 ele retorna em alguns formatos específicos, acho que para evitar tratamento de strings no hardware é melhor adaptar no site, deem uma olhada no formato que vamos enviar (publicar) no documento em anexo. Onde ele fala da resposta que será enviada inicia na pagina 10 e vai até a 12.

[GNSS](https://www.elecrow.com/download/SIM800%20Series_GNSS_Application%20Note%20V1.00.pdf)

**Comment by camilanovaes** [comment]
Feito :slightly_smiling_face:
