### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by felipebastosb** [lasseufpa/circular#5]
Segue os links de alguns materiais sobre android.

[Playlist AndroidStudio](https://www.youtube.com/watch?v=Ikqej0bYdGA)

[Apostila Android I](http://othonbatista.com/arquivos/android/apostila-android.pdf)

[Android Pro](http://www.androidpro.com.br/android-studio-configurando-ambiente/)

**Comment by albertklik** [comment]
[hello-android_p1_0.pdf](https://github.com/lasseufpa/circular/files/534961/hello-android_p1_0.pdf)
Livro Hello Android - material Android em Inglês.
